# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8500a078706e9d7cf82b0f6049c3febf3bdef8e986c9455dfe0f73582f1761faa1482f33b3733a973941bd0860b54a19050d04e7e8315f8c835da793aa6569d

test:
  secret_key_base: 62c568d1f3e2b02e5a995d8c7452be05691db6d633d5a303d96bb42f4d51f9edd83ef746a6e201ca29958dbc226d715ae2bd382b839ed856f6c764ce909553b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
